
name: doctor_call_app_v2
description: "Doctor Call App v2 - Flutter Web Dashboard for Hospital Management"
publish_to: 'none' # Private package

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Web-compatible UI icons
  cupertino_icons: ^1.0.8
  
  # HTTP requests and API integration
  http: ^1.1.0
  dio: ^5.3.2
  
  # Web-compatible local storage
  shared_preferences: ^2.2.3
  
  # State management
  provider: ^6.1.2
  
  # UI components and animations
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  shimmer: ^3.0.0
  
  # Authentication and secure storage
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
