
name: doctor_call_app_v2
description: "Doctor Call App v2 - Flutter Web Dashboard for Hospital Management"
publish_to: 'none' # Private package

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Web-compatible UI icons
  cupertino_icons: ^1.0.8
  
  # Web-compatible local storage
  shared_preferences: ^2.2.3
  
  # State management
  provider: ^6.1.2
  http: ^1.5.0
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
