name: Doctor Call App CI/CD

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./doctor_call_app_v2
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Analyze code
        run: flutter analyze
        
      - name: Format check
        run: dart format --output=none --set-exit-if-changed .
        
      - name: Run unit tests
        run: flutter test --coverage
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

  build-web:
    name: Build Web Version
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: ./doctor_call_app_v2
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build web
        run: flutter build web --release --base-href "/"
        
      - name: Deploy to GitHub Pages (Public)
        if: github.repository_owner != 'private'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          cname: doctor-call.your-domain.com  # اختياري: ضع النطاق المخصص

  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: ./doctor_call_app_v2
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --release
        
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: doctor-call-app.apk
          path: doctor_call_app_v2/build/app/outputs/flutter-apk/app-release.apk

  deploy-private:
    name: Deploy to Private Repository
    runs-on: ubuntu-latest
    needs: [test, build-web]
    if: github.ref == 'refs/heads/master' && github.repository == 'Alebrahimi2/doctor-call-app'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build for production
        run: |
          flutter build web --release
          flutter build apk --release
          
      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp -r build/web deployment/
          cp build/app/outputs/flutter-apk/app-release.apk deployment/
          
      - name: Archive deployment
        uses: actions/upload-artifact@v4
        with:
          name: doctor-call-deployment
          path: deployment/
          
  sync-to-public:
    name: Sync Web Build to Public Repository
    runs-on: ubuntu-latest
    needs: build-web
    if: github.ref == 'refs/heads/master' && github.repository == 'Alebrahimi2/doctor-call-app'
    
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build web for public
        run: flutter build web --release
        
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          repository: Alebrahimi2/doctor-call-web
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          path: public-repo
          
      - name: Copy web build to public repo
        run: |
          rm -rf public-repo/*
          cp -r build/web/* public-repo/
          
      - name: Commit and push to public repo
        run: |
          cd public-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Deploy from private repo - $(date)" || exit 0
          git push

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'